
[origins]

	[origins."origins-classes:nitwit"]
		enabled = true

	[origins."strictly:wildcat"]
		enabled = true
		"strictly:feline_grace" = true
		"strictly:feared_hunter" = true
		"strictly:soft_paws" = true
		"origins:climbing" = true
		"strictly:night_hunter" = true
		"origins:carnivore" = true
		"strictly:water_weary" = true

	[origins."origins:enderian"]
		enabled = true
		"origins:throw_ender_pearl" = true
		"origins:water_vulnerability" = true
		"origins:pumpkin_hate" = true
		"origins:extra_reach" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true

	[origins."origins:feline"]
		enabled = true
		"origins:fall_immunity" = true
		"origins:sprint_jump" = true
		"origins:velvet_paws" = true
		"origins:nine_lives" = true
		"origins:weak_arms" = true
		"origins:scare_creepers" = true
		"origins:cat_vision" = true

	[origins."origins-classes:warrior"]
		enabled = true
		"origins-classes:more_attack_damage" = true
		"origins-classes:less_shield_slowdown" = true

	[origins."origins:elytrian"]
		enabled = true
		"origins:elytra" = true
		"origins:launch_into_air" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:claustrophobia" = true
		"origins:more_kinetic_damage" = true

	[origins."origins-classes:explorer"]
		enabled = true
		"origins-classes:explorer_kit" = true
		"origins-classes:no_sprint_exhaustion" = true

	[origins."strictly:knight"]
		enabled = true
		"strictly:skofnung" = true
		"strictly:skilled_swordsman" = true
		"strictly:valour" = true
		"strictly:burdened" = true
		"strictly:bowless" = true
		"strictly:book" = true
		"strictly:crescent_worship" = true

	[origins."strictly:paladin"]
		enabled = true
		"strictly:holy_fire" = true
		"strictly:dried_out" = true
		"strictly:leech" = true
		"strictly:well_built" = true
		"strictly:durendal" = true
		"strictly:skilled_swordsman_1" = true
		"strictly:book" = true
		"strictly:praise_the_sun" = true

	[origins."origins:phantom"]
		enabled = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:phasing" = true
		"origins:invisibility" = true
		"origins:burn_in_daylight" = true
		"origins:hunger_over_time" = true
		"origins:fragile" = true
		"origins:phantomize_overlay" = true

	[origins."origins-classes:beastmaster"]
		enabled = true
		"origins-classes:tamed_animal_boost" = true
		"origins-classes:tamed_potion_diffusal" = true

	[origins."origins-classes:merchant"]
		enabled = true
		"origins-classes:trade_availability" = true
		"origins-classes:rare_wandering_loot" = true

	[origins."strictly:priest"]
		enabled = true
		"strictly:scholar" = true
		"strictly:nimble" = true
		"origins:vegetarian" = true
		"origins:fall_immunity" = true
		"strictly:holy_curse" = true
		"origins:ender_particles" = true

	[origins."strictly:adapted_raccoon"]
		enabled = true
		"strictly:arrow_weak" = true
		"strictly:claustrophobia" = true
		"strictly:expert_at_hiding" = true
		"strictly:hates_carrots" = true
		"strictly:nocturnal_eyes1" = true
		"strictly:nocturnal" = true
		"strictly:rabies_resistant" = true
		"strictly:rabies" = true
		"strictly:scurry" = true
		"strictly:rabies_cont" = true
		"strictly:sharp_claws" = true
		"strictly:small_body" = true
		"strictly:small_hands" = true
		"strictly:thick_fur" = true
		"strictly:tough_heart" = true
		"strictly:tough_stomach" = true
		"strictly:trash_lover" = true
		"strictly:jump2" = true
		"strictly:step_height" = true

	[origins."strictly:birdofparadise"]
		enabled = true
		"strictly:winged" = true
		"strictly:angelicgrace" = true
		"origins:aerial_combatant" = true
		"origins:tailwind" = true
		"strictly:wet_wings" = true
		"strictly:windsblessing" = true

	[origins."origins-classes:rancher"]
		enabled = true
		"origins-classes:twin_breeding" = true
		"origins-classes:more_animal_loot" = true

	[origins."origins:blazeborn"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:nether_spawn" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:damage_from_snowballs" = true
		"origins:damage_from_potions" = true

	[origins."origins:avian"]
		enabled = true
		"origins:slow_falling" = true
		"origins:fresh_air" = true
		"origins:like_air" = true
		"origins:tailwind" = true
		"origins:lay_eggs" = true
		"origins:vegetarian" = true

	[origins."origins-classes:archer"]
		enabled = true
		"origins-classes:no_projectile_divergence" = true
		"origins-classes:less_bow_slowdown" = true

	[origins."origins-classes:farmer"]
		enabled = true
		"origins-classes:more_crop_drops" = true
		"origins-classes:better_bone_meal" = true

	[origins."strictly:dwarf"]
		enabled = true
		"strictly:haste" = true
		"strictly:potent_brew" = true
		"strictly:miniature_dwarf" = true
		"strictly:dense" = true
		"strictly:insatiable_hunger" = true
		"strictly:gold_lover" = true
		"strictly:nocturnal_eyes1" = true
		"strictly:pickaxeless_stone" = true
		"strictly:jump" = true
		"strictly:step_height" = true

	[origins."strictly:high_elf"]
		enabled = true
		"strictly:flamethrower" = true
		"strictly:forest_vision" = true
		"strictly:hyper_sight" = true
		"strictly:towering" = true
		"strictly:vegetarian" = true
		"strictly:spindly" = true
		"strictly:jump3" = true
		"strictly:falldmg" = true

	[origins."origins-classes:miner"]
		enabled = true
		"origins-classes:more_stone_break_speed" = true
		"origins-classes:no_mining_exhaustion" = true

	[origins."origins-classes:cook"]
		enabled = true
		"origins-classes:better_crafted_food" = true
		"origins-classes:more_smoker_xp" = true

	[origins."strictly:troll"]
		enabled = true
		"strictly:lead_belly" = true
		"strictly:stocky" = true
		"strictly:gargantuan" = true
		"strictly:ravenous" = true
		"strictly:sluggish" = true
		"strictly:xxxl" = true
		"strictly:unweildy" = true
		"strictly:cunning_hidden" = true

	[origins."origins:human"]
		enabled = true

	[origins."origins-classes:lumberjack"]
		enabled = true
		"origins-classes:tree_felling" = true
		"origins-classes:more_planks_from_logs" = true

	[origins."origins:shulk"]
		enabled = true
		"origins:shulker_inventory" = true
		"origins:natural_armor" = true
		"origins:strong_arms" = true
		"origins:strong_arms_break_speed" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true

	[origins."origins-classes:cleric"]
		enabled = true
		"origins-classes:potion_bonus" = true
		"origins-classes:better_enchanting" = true

	[origins."strictly:buzz"]
		enabled = true
		"strictly:stinger" = true
		"strictly:bee_diet" = true
		"strictly:bee_skin" = true
		"strictly:freedom_calls" = true
		"strictly:itty_bitty" = true
		"strictly:nectar_processing" = true
		"strictly:new_diet" = true
		"strictly:smoke_sickness" = true

	[origins."origins:merling"]
		enabled = true
		"origins:water_breathing" = true
		"origins:water_vision" = true
		"origins:aqua_affinity" = true
		"origins:swim_speed" = true
		"origins:like_water" = true
		"origins:aquatic" = true
		"origins:conduit_power_on_land" = true
		"origins:air_from_potions" = true

	[origins."origins:arachnid"]
		enabled = true
		"origins:climbing" = true
		"origins:master_of_webs" = true
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true

	[origins."strictly:otter"]
		enabled = true
		"origins:aqua_affinity" = true
		"origins:aquatic" = true
		"origins:swim_speed" = true
		"origins:like_water" = true
		"origins:no_shield" = true
		"strictly:improved_lungs" = true
		"strictly:aquatic_predator" = true
		"strictly:otter_gods_blessing" = true
		"strictly:otter_pouch" = true
		"origins:claustrophobia" = true
		"strictly:heart_reduction" = true
		"strictly:mini_riptide" = true
		"strictly:miniature_dwarf" = true
		"strictly:land_slow" = true
		"strictly:jump" = true
		"strictly:step_height" = true

	[origins."strictly:thief"]
		enabled = true
		"origins:shulker_inventory" = true
		"strictly:superstealth" = true
		"origins:tailwind" = true
		"origins:fragile" = true
		"strictly:cloak" = true
		"strictly:money_lover" = true
		"strictly:strong" = true
		"origins:more_exhaustion" = true
		"strictly:night-owl" = true

	[origins."strictly:umvuthi"]
		enabled = true
		"strictly:sunblessing" = true
		"strictly:sun_block" = true
		"strictly:weak_health" = true
		"strictly:vegetarian1" = true

	[origins."origins-classes:blacksmith"]
		enabled = true
		"origins-classes:quality_equipment" = true
		"origins-classes:efficient_repairs" = true

	[origins."strictly:plantaemancer"]
		enabled = true
		"strictly:poison_ivy_vines" = true
		"strictly:plant_caretaker" = true
		"strictly:regrowth" = true
		"strictly:flammable" = true
		"strictly:light_deprivation" = true
		"strictly:blissful_light" = true

	[origins."origins-classes:rogue"]
		enabled = true
		"origins-classes:sneaky" = true
		"origins-classes:stealth" = true
		"origins-classes:stealth_core" = true

