
[General]
	#Render the with Area Card selected corners in world.
	enable_area_card_corner_rendering = true
	#Should the quarry gui screen be rendered in Dark Mode.
	enable_quarry_darkmode = false
	#Enable dark mode button.
	enable_quarry_darkmode_button = true

