
# This category holds configs that uses lists.
["List Config Options"]
	#Determines the minimum number of Houndmasters that can spawn in each raid wave.
	#This is meant to be a list of seven integers.
	#A list of less than seven will fill remaining spots with zeroes, and values past the seventh will be ignored.
	houndmaster_raid_wave_counts = [0, 0, 0, 0, 1, 1, 2]
	#Determines which structure template pools will have the dog structures located under "all_bark_all_bite:village/common/animals" injected into them.
	#Making this empty prevents the dog structures from being injected into any structure template pools.
	dog_template_pool_targets = ["minecraft:village/common/cats"]
	#Determines which structure template pools will have the kennel structure located under "all_bark_all_bite:pillager_outpost/feature_kennel" injected into them.
	#Making this empty prevents the kennel structure from being injected into any structure template pools.
	kennel_template_pool_targets = ["minecraft:pillager_outpost/features"]

